// Decisions repository — minimal Phase 3 stub per Open Question 2. The
// table is irreplaceable user data per Pitfall 7; Phase 4 owns the full
// CLI/MCP surface (decision-add, decision-review, outcome-record).
// Phase 3 ships the file so the schema migration has a typed write surface
// and the Plan 03-10 contract tests can exercise the table end-to-end.
//
// Surface for this phase: insert(d), byId(id), listOpen(). Phase 4 will
// extend with updateOutcome(id, status, notes), byCategory(category),
// search(query), etc. The ULID id is generated by the (future) Phase 4
// decision-add service before calling insert(); Phase 3 trusts the
// caller to pass a valid ULID string.

import { desc, eq } from 'drizzle-orm';
import type { drizzle } from 'drizzle-orm/better-sqlite3';
import type { Decision } from '../../../domain/types/entities.js';
import { decisions as decisionsTable } from '../schema.js';

export interface DecisionsRepo {
  /** Insert a new decision. Throws on PK collision — ULID generation is
   *  the caller's responsibility and is collision-resistant in practice. */
  insert(d: {
    id: string;
    createdAt: string;
    category: string;
    decision: string;
    rationale: string | null;
    confidence: 'low' | 'medium' | 'high' | null;
    expectedEffect: string | null;
    followUpDate: string | null;
  }): void;
  /** Point lookup; null when the id is absent. */
  byId(id: string): Decision | null;
  /** Open-status decisions, newest first. Phase 5 doctor surfaces the
   *  count as a data-quality signal. */
  listOpen(): Decision[];
}

type DecisionRow = typeof decisionsTable.$inferSelect;

export function createDecisionsRepo(db: ReturnType<typeof drizzle>): DecisionsRepo {
  return {
    insert(d): void {
      db.transaction(
        (tx) => {
          tx.insert(decisionsTable)
            .values({
              id: d.id,
              created_at: d.createdAt,
              category: d.category,
              decision: d.decision,
              rationale: d.rationale,
              confidence: d.confidence,
              expected_effect: d.expectedEffect,
              follow_up_date: d.followUpDate,
              // status defaults to 'open' at the schema layer; outcome_notes
              // stays null until Phase 4's updateOutcome flow lands.
            })
            .run();
        },
        { behavior: 'immediate' },
      );
    },

    byId(id: string): Decision | null {
      const row = db.select().from(decisionsTable).where(eq(decisionsTable.id, id)).get();
      return row ? rowToDecision(row) : null;
    },

    listOpen(): Decision[] {
      const rows = db
        .select()
        .from(decisionsTable)
        .where(eq(decisionsTable.status, 'open'))
        .orderBy(desc(decisionsTable.created_at))
        .all();
      return rows.map(rowToDecision);
    },
  };
}

function rowToDecision(row: DecisionRow): Decision {
  return {
    id: row.id,
    createdAt: row.created_at,
    category: row.category,
    decision: row.decision,
    rationale: row.rationale,
    confidence: row.confidence,
    expectedEffect: row.expected_effect,
    followUpDate: row.follow_up_date,
    status: row.status,
    outcomeNotes: row.outcome_notes,
  };
}
