// REV-08 / D-26 — banned-word lint on RENDERED formatter output.
//
// Defence-in-depth Layer 2 of the ADR-0005 §Enforcement strategy:
//
//   Layer 1 (source-level):   scripts/ci-grep-gates.sh Gate A scans every
//                              .ts / .md file for the 10 banned tokens.
//   Layer 2 (rendered-level): THIS file runs every formatter on every
//                              relevant fixture and re-checks the
//                              RENDERED output for banned tokens + emoji.
//
// Why both: source-grep catches static strings but cannot see content
// generated by string concatenation (a catalog entry interpolated into a
// template). Layer 2 closes that gap by exercising the full pipeline
// fixture → service → formatter → string and lint-checking the output.
//
// The contract test also runs the lint against the three catalog
// modules (ACTION_CATALOG, DECISION_PROMPT_CATALOG, API_GAP_ENTRIES) at
// module load — same as the per-module sibling tests in Plan 04-05 /
// 04-06, but consolidated here so a single failing assertion identifies
// the offending catalog entry by id.
//
// Plan 04-10 will extend this test with the 4 prompt-instruction
// constants once they land (PROMPT_INSTRUCTIONS at the MCP prompt
// surface). Until then the prompt subset is intentionally empty.
//
// Pure (no I/O outside readFileSync + the in-memory DB helpers used by
// the daily/weekly arms). No console.*, no process.stdout.write.

import { readdirSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { Logger } from 'pino';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { ACTION_CATALOG } from '../../src/domain/actions/catalog.js';
import { DECISION_PROMPT_CATALOG } from '../../src/domain/actions/decision-prompts.js';
import {
  BANNED_TONE_WORDS,
  BANNED_TONE_WORDS_SET,
  containsBannedToneToken,
  EMOJI_RE,
} from '../../src/domain/banned-words.js';
import type { Decision } from '../../src/domain/types/entities.js';
import { renderApiGap } from '../../src/formatters/api-gap.txt.js';
import { renderDailyReview } from '../../src/formatters/daily-review.txt.js';
import {
  renderDecisionDetail,
  renderDecisionList,
  renderDecisionUpdate,
} from '../../src/formatters/decision.txt.js';
import { renderDoctor } from '../../src/formatters/doctor.txt.js';
import { renderWeeklyReview } from '../../src/formatters/weekly-review.txt.js';
import { createBodyMeasurementsRepo } from '../../src/infrastructure/db/repositories/body-measurements.repo.js';
import { createCyclesRepo } from '../../src/infrastructure/db/repositories/cycles.repo.js';
import { createDailySummariesRepo } from '../../src/infrastructure/db/repositories/daily-summaries.repo.js';
import { createDecisionsRepo } from '../../src/infrastructure/db/repositories/decisions.repo.js';
import { createProfileRepo } from '../../src/infrastructure/db/repositories/profile.repo.js';
import { createRecoveryRepo } from '../../src/infrastructure/db/repositories/recovery.repo.js';
import { createSleepsRepo } from '../../src/infrastructure/db/repositories/sleep.repo.js';
import { createSyncRunsRepo } from '../../src/infrastructure/db/repositories/sync-runs.repo.js';
import { createWorkoutsRepo } from '../../src/infrastructure/db/repositories/workouts.repo.js';
import { API_GAP_ENTRIES } from '../../src/services/api-gap/data.js';
import { getApiGap } from '../../src/services/api-gap/index.js';
import { type DailyReviewDeps, getDailyReview } from '../../src/services/review/daily.js';
import { getWeeklyReview, type WeeklyReviewDeps } from '../../src/services/review/weekly.js';
import { type DailyFixtureSpec, expandDailyFixture } from '../fixtures/review/_generators/daily.js';
import {
  expandWeeklyFixture,
  type WeeklyFixtureSpec,
} from '../fixtures/review/_generators/weekly.js';
import { createInMemoryDb, type InMemoryDbResult } from '../helpers/in-memory-db.js';

const REVIEW_FIXTURES_DIR = resolve(__dirname, '..', 'fixtures', 'review');
const DECISION_FIXTURES_DIR = resolve(__dirname, '..', 'fixtures', 'decisions');

// ---------------------------------------------------------------------------
// Helpers.
// ---------------------------------------------------------------------------

function listFixtureFiles(dir: string, prefix: string): string[] {
  return readdirSync(dir)
    .filter((name) => name.startsWith(prefix) && name.endsWith('.json'))
    .sort();
}

function makeStubLogger(): Logger {
  const noop = vi.fn();
  return {
    info: noop,
    warn: noop,
    error: noop,
    debug: noop,
    trace: noop,
    fatal: noop,
    child: () => makeStubLogger(),
  } as unknown as Logger;
}

function makeDailyDeps(mem: InMemoryDbResult): DailyReviewDeps {
  const repos = {
    cycles: createCyclesRepo(mem.db),
    recoveries: createRecoveryRepo(mem.db),
    sleeps: createSleepsRepo(mem.db),
    workouts: createWorkoutsRepo(mem.db),
    profile: createProfileRepo(mem.db),
    bodyMeasurements: createBodyMeasurementsRepo(mem.db),
    syncRuns: createSyncRunsRepo(mem.db),
    dailySummaries: createDailySummariesRepo(mem.db),
  };
  return {
    repos,
    clock: () => new Date('2026-03-15T15:00:00.000Z'),
    logger: makeStubLogger(),
  };
}

function makeWeeklyDeps(mem: InMemoryDbResult): WeeklyReviewDeps {
  const repos = {
    cycles: createCyclesRepo(mem.db),
    recoveries: createRecoveryRepo(mem.db),
    sleeps: createSleepsRepo(mem.db),
    workouts: createWorkoutsRepo(mem.db),
    profile: createProfileRepo(mem.db),
    bodyMeasurements: createBodyMeasurementsRepo(mem.db),
    syncRuns: createSyncRunsRepo(mem.db),
    decisions: createDecisionsRepo(mem.db),
    dailySummaries: createDailySummariesRepo(mem.db),
  };
  return {
    repos,
    clock: () => new Date('2026-03-15T15:00:00.000Z'),
    ianaZone: () => 'America/Los_Angeles',
    logger: makeStubLogger(),
  };
}

function assertCleanRendered(rendered: string, label: string): void {
  const hit = containsBannedToneToken(rendered);
  const context =
    hit.hit && 'index' in hit ? rendered.slice(Math.max(0, hit.index - 30), hit.index + 30) : '';
  expect(
    hit.hit,
    hit.hit && 'word' in hit
      ? `Banned token '${hit.word}' found in ${label}: ...${context}...`
      : `Banned token found in ${label}`,
  ).toBe(false);
  expect(EMOJI_RE.test(rendered), `Emoji match in ${label}`).toBe(false);
}

// ---------------------------------------------------------------------------
// Sanity (carry forward from Wave 0).
// ---------------------------------------------------------------------------

describe('Phase 4 formatter tone contract — sanity', () => {
  it('BANNED_TONE_WORDS exposes 10 entries (the ADR-0005 canonical list)', () => {
    expect(BANNED_TONE_WORDS).toHaveLength(10);
    expect(BANNED_TONE_WORDS_SET.size).toBe(10);
  });

  it('helpers are importable and shaped correctly', () => {
    expect(typeof containsBannedToneToken).toBe('function');
    expect(EMOJI_RE).toBeInstanceOf(RegExp);
  });
});

// ---------------------------------------------------------------------------
// Catalog source-level lint (ADR-0005 §Enforcement bullet 1).
// ---------------------------------------------------------------------------

describe('catalog source-level lint — ACTION_CATALOG entries', () => {
  for (const entry of ACTION_CATALOG) {
    it(`ACTION_CATALOG[${entry.id}] text passes tone lint`, () => {
      assertCleanRendered(entry.text, `ACTION_CATALOG[${entry.id}]`);
    });
  }
});

describe('catalog source-level lint — DECISION_PROMPT_CATALOG entries', () => {
  for (const entry of DECISION_PROMPT_CATALOG) {
    it(`DECISION_PROMPT_CATALOG[${entry.id}] text passes tone lint`, () => {
      assertCleanRendered(entry.text, `DECISION_PROMPT_CATALOG[${entry.id}]`);
    });
  }
});

describe('catalog source-level lint — API_GAP_ENTRIES entries', () => {
  for (const entry of API_GAP_ENTRIES) {
    it(`API_GAP_ENTRIES[${entry.feature}] all string fields pass tone lint`, () => {
      assertCleanRendered(entry.feature, `API_GAP_ENTRIES[${entry.feature}].feature`);
      assertCleanRendered(
        entry.whoop_consumer_path,
        `API_GAP_ENTRIES[${entry.feature}].whoop_consumer_path`,
      );
      assertCleanRendered(entry.notes, `API_GAP_ENTRIES[${entry.feature}].notes`);
      if (entry.alternative_via_v2 !== null) {
        assertCleanRendered(
          entry.alternative_via_v2,
          `API_GAP_ENTRIES[${entry.feature}].alternative_via_v2`,
        );
      }
    });
  }
});

// ---------------------------------------------------------------------------
// Rendered-output lint — Daily review.
// ---------------------------------------------------------------------------

describe('rendered-output lint — renderDailyReview × every daily fixture', () => {
  const fixtures = listFixtureFiles(REVIEW_FIXTURES_DIR, 'daily-');
  let mem: InMemoryDbResult;
  let deps: DailyReviewDeps;

  beforeEach(() => {
    mem = createInMemoryDb();
    deps = makeDailyDeps(mem);
  });
  afterEach(() => mem.close());

  for (const fixtureFile of fixtures) {
    it(`${fixtureFile} → rendered output free of banned tokens + emoji`, async () => {
      const spec = JSON.parse(
        readFileSync(resolve(REVIEW_FIXTURES_DIR, fixtureFile), 'utf-8'),
      ) as DailyFixtureSpec;
      const expanded = expandDailyFixture(spec);
      deps.repos.cycles.upsertBatch(expanded.cycles);
      deps.repos.recoveries.upsertBatch(expanded.recoveries);
      deps.repos.sleeps.upsertBatch(expanded.sleeps);
      const result = await getDailyReview({ date: spec.reviewed_date }, deps);
      const rendered = renderDailyReview(result);
      assertCleanRendered(rendered, `renderDailyReview(${fixtureFile})`);
    });
  }
});

// ---------------------------------------------------------------------------
// Rendered-output lint — Weekly review.
// ---------------------------------------------------------------------------

describe('rendered-output lint — renderWeeklyReview × every weekly fixture', () => {
  const fixtures = listFixtureFiles(REVIEW_FIXTURES_DIR, 'weekly-');
  let mem: InMemoryDbResult;
  let deps: WeeklyReviewDeps;

  beforeEach(() => {
    mem = createInMemoryDb();
    deps = makeWeeklyDeps(mem);
  });
  afterEach(() => mem.close());

  for (const fixtureFile of fixtures) {
    it(`${fixtureFile} → rendered output free of banned tokens + emoji`, async () => {
      const spec = JSON.parse(
        readFileSync(resolve(REVIEW_FIXTURES_DIR, fixtureFile), 'utf-8'),
      ) as WeeklyFixtureSpec;
      const expanded = expandWeeklyFixture(spec);
      deps.repos.cycles.upsertBatch(expanded.cycles);
      deps.repos.recoveries.upsertBatch(expanded.recoveries);
      deps.repos.sleeps.upsertBatch(expanded.sleeps);
      deps.repos.workouts.upsertBatch(expanded.workouts);
      const result = await getWeeklyReview({ date: spec.reviewed_date }, deps);
      const rendered = renderWeeklyReview(result);
      assertCleanRendered(rendered, `renderWeeklyReview(${fixtureFile})`);
    });
  }
});

// ---------------------------------------------------------------------------
// Rendered-output lint — Decision formatter (3 shapes × 3 fixtures).
// ---------------------------------------------------------------------------

describe('rendered-output lint — renderDecisionList / Detail / Update × every decision fixture', () => {
  const fixtureFiles = listFixtureFiles(DECISION_FIXTURES_DIR, 'decision-');

  for (const fixtureFile of fixtureFiles) {
    it(`${fixtureFile} → list-mode rendered output (when decisions[] available) free of banned tokens`, () => {
      const fx = JSON.parse(readFileSync(resolve(DECISION_FIXTURES_DIR, fixtureFile), 'utf-8')) as {
        decisions?: Decision[];
        decision?: Decision;
        result?: { mode: 'update'; decision: Decision };
      };
      if (fx.decisions !== undefined) {
        const rendered = renderDecisionList(fx.decisions, new Date('2026-03-15T15:00:00.000Z'));
        assertCleanRendered(rendered, `renderDecisionList(${fixtureFile})`);
      }
      if (fx.decision !== undefined) {
        const rendered = renderDecisionDetail(fx.decision);
        assertCleanRendered(rendered, `renderDecisionDetail(${fixtureFile})`);
      }
      if (fx.result !== undefined && fx.result.mode === 'update') {
        const rendered = renderDecisionUpdate(fx.result.decision);
        assertCleanRendered(rendered, `renderDecisionUpdate(${fixtureFile})`);
      }
    });
  }
});

// ---------------------------------------------------------------------------
// Rendered-output lint — API-gap formatter.
// ---------------------------------------------------------------------------

describe('rendered-output lint — renderApiGap', () => {
  it('full catalog rendered output free of banned tokens + emoji', async () => {
    const result = await getApiGap();
    const rendered = renderApiGap(result);
    assertCleanRendered(rendered, 'renderApiGap(full catalog)');
  });
});

// ---------------------------------------------------------------------------
// Rendered-output lint — Phase 1-3 formatters (retroactive D-26 coverage
// per Plan 04-09 success_criteria).
// ---------------------------------------------------------------------------

describe('rendered-output lint — Phase 1-3 formatters (retroactive D-26 coverage)', () => {
  it('renderDoctor full pass/warn/fail result free of banned tokens', () => {
    // Construct a representative DoctorResult inline — no fixture file
    // exists, and the formatter is pure (no DB needed).
    const result = {
      overall: 'warn' as const,
      checks: [
        { name: 'env_vars', status: 'pass' as const, detail: 'all required env vars set' },
        {
          name: 'token_storage',
          status: 'warn' as const,
          detail: 'using file fallback, not OS keyring',
        },
        {
          name: 'whoop_connectivity',
          status: 'fail' as const,
          detail: 'auth required: run `recovery-ledger auth`',
        },
      ],
    };
    const rendered = renderDoctor(result);
    assertCleanRendered(rendered, 'renderDoctor');
  });
});

// ---------------------------------------------------------------------------
// Wave 4 placeholder (Plan 04-10 will extend with prompt-instruction
// constants).
//
// PROMPT_INSTRUCTIONS source: src/mcp/prompts/* — does not exist until
// Plan 04-10 lands. This describe block is intentionally empty so the
// extension lands by adding an iteration over the (then-existing)
// PROMPT_INSTRUCTIONS array.
// ---------------------------------------------------------------------------

describe('Wave 4 placeholder — prompt-instruction lint (Plan 04-10 extension)', () => {
  it('placeholder for PROMPT_INSTRUCTIONS lint — populated by Plan 04-10', () => {
    // No-op assertion to keep the describe block visible in test output;
    // Plan 04-10 will replace this with an it.each over the constants.
    expect(true).toBe(true);
  });
});
